import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
const source=fs.readFileSync(new URL('../native-ui.js',import.meta.url),'utf8');
class Element {
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.nodeType=1;this.children=[];this.attrs=new Map();this.dataset={};this.listeners={};this.hidden=false;this.animations=[];this.complete=false;this.naturalWidth=0;const names=new Set();this.classList={add:(...s)=>s.forEach(x=>names.add(x)),remove:(...s)=>s.forEach(x=>names.delete(x)),contains:x=>names.has(x)};}
 get className(){return this._class||''}set className(x){this._class=x;this.classList.add(...x.split(' '))}
 getAttribute(k){return this.attrs.get(k)??null}setAttribute(k,v){this.attrs.set(k,String(v))}removeAttribute(k){this.attrs.delete(k)}hasAttribute(k){return this.attrs.has(k)}toggleAttribute(k,v){if(v)this.setAttribute(k,'');else this.removeAttribute(k)}
 append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n)}}replaceChildren(...nodes){for(const n of this.children)n.parent=null;this.children=[];this.append(...nodes)}remove(){if(this.parent){this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=null}}
 matches(s){if(s===':disabled,[aria-disabled="true"]')return !!this.disabled||this.getAttribute('aria-disabled')==='true';if(s.includes('#heroImage')&&this.tagName==='IMG')return true;return s.split(',').some(x=>x==='button'&&this.tagName==='BUTTON'||x==='a[href]'&&this.tagName==='A'&&this.hasAttribute('href'));}
 closest(s){if(s==='[inert]')return null;if(s.includes('.product-image'))return this.frame||null;return this.matches(s)?this:null}
 querySelectorAll(){return []}addEventListener(k,cb){(this.listeners[k]||=[]).push(cb)}emit(k,e={}){for(const cb of this.listeners[k]||[])cb(e)}
 animate(frames,opts){const a={frames,opts,finished:Promise.resolve(),cancel(){this.cancelled=true}};this.animations.push(a);return a}
}
function setup(){const document=new Element(),window=new Element(),frames=new Map();let next=0;document.documentElement=new Element();document.readyState='loading';document.createElement=tag=>new Element(tag);document.getElementById=()=>null;const media=new Element();media.matches=false;const observers=[];
const context={document,window,matchMedia:()=>media,CSS:{supports:()=>true},MutationObserver:class{constructor(cb){this.cb=cb;observers.push(this)}observe(){}},requestAnimationFrame:cb=>{frames.set(++next,cb);return next},cancelAnimationFrame:id=>frames.delete(id),console};vm.runInNewContext(source,context);
return {document,window,media,observers,api:window.HAKI_UI,paint(){const pending=[...frames.values()];frames.clear();pending.forEach(cb=>cb())},event(name,target,extras={}){document.emit(name,{target,pointerId:1,isPrimary:true,button:0,clientX:0,clientY:0,...extras})}}}

test('Fast cached results produce no skeleton or delayed animation',()=>{const h=setup(),el=new Element();const finish=h.api.begin(el);finish();h.paint();assert.equal(el.children.length,0);assert.equal(el.hasAttribute('aria-busy'),false);assert.equal(el.animations.length,0)});
test('Slow empty lists get shaped placeholders and reveal the real content',()=>{const h=setup(),el=new Element(),metric=new Element();const finish=h.api.begin(el,'inventory',8,{metrics:[metric]});h.paint();assert.equal(el.children[0].dataset.shape,'inventory');assert.equal(el.children[0].children.length,8);assert.equal(el.children[0].getAttribute('aria-hidden'),'true');assert.equal(metric.hasAttribute('data-haki-metric-pending'),true);el.replaceChildren(new Element());finish();assert.equal(el.children.length,1);assert.equal(metric.hasAttribute('data-haki-metric-pending'),false);assert.equal(el.animations.length,1)});
test('Stale finish cannot remove a newer pending request',()=>{const h=setup(),el=new Element();const old=h.api.begin(el);h.paint();const current=h.api.begin(el,'days',7,{reset:true});h.paint();old();assert.equal(el.children[0].children.length,7);assert.equal(el.getAttribute('aria-busy'),'true');current(false);assert.equal(el.hasAttribute('aria-busy'),false);assert.equal(el.children[0].textContent.includes('No se pudo cargar'),true)});
test('Refreshing available content does not replace it or mask real metrics',()=>{const h=setup(),el=new Element(),real=new Element(),metric=new Element();el.append(real);const finish=h.api.begin(el,'rows',4,{metrics:[metric]});h.paint();assert.equal(el.children[0],real);assert.equal(metric.hasAttribute('data-haki-metric-pending'),false);finish();assert.equal(el.animations.length,0)});
test('Repeated presses preserve clicks and never leave buttons compressed',()=>{const h=setup(),button=new Element('button');let clicks=0;button.addEventListener('click',()=>clicks++);for(let i=0;i<20;i++){h.event('pointerdown',button);assert.equal(button.classList.contains('haki-pressed'),true);h.event('pointerup',button);button.emit('click');assert.equal(button.classList.contains('haki-pressed'),false)}assert.equal(clicks,20);assert.ok(button.animations.every(a=>a.frames[0].scale==='.98'));});
test('Scrolling, cancellation and window blur release pressure; disabled controls are ignored',()=>{const h=setup(),button=new Element('button');button.disabled=true;h.event('pointerdown',button);assert.equal(button.classList.contains('haki-pressed'),false);button.disabled=false;h.event('pointerdown',button);h.event('pointermove',button,{clientX:15});assert.equal(button.classList.contains('haki-pressed'),false);h.event('pointerdown',button);h.event('pointercancel',button);assert.equal(button.classList.contains('haki-pressed'),false);h.event('pointerdown',button);h.window.emit('blur');assert.equal(button.classList.contains('haki-pressed'),false)});
test('Reduced motion avoids JavaScript reveal and release animations',()=>{const h=setup(),button=new Element('button');h.media.matches=true;h.api.reveal(button);h.event('pointerdown',button);h.event('pointerup',button);assert.equal(button.animations.length,0)});
test('Keyboard feedback does not intercept activation and always releases',()=>{const h=setup(),button=new Element('button');h.event('keydown',button,{key:'Enter'});assert.equal(button.classList.contains('haki-pressed'),true);h.event('keyup',button,{key:'Enter'});assert.equal(button.classList.contains('haki-pressed'),false)});
test('Image placeholders skip cached images and clear errors without changing src',()=>{const h=setup(),img=new Element('img'),frame=new Element();img.frame=frame;img.setAttribute('src','photo.webp');img.complete=true;img.naturalWidth=400;h.observers[0].cb([{type:'attributes',target:img}]);assert.equal(img.hasAttribute('data-haki-image-pending'),false);img.complete=false;img.naturalWidth=0;h.observers[0].cb([{type:'attributes',target:img}]);assert.equal(frame.hasAttribute('data-haki-image-pending'),true);img.emit('error');assert.equal(frame.hasAttribute('data-haki-image-pending'),false);assert.equal(img.getAttribute('src'),'photo.webp');img.setAttribute('src','fallback.webp');h.observers[0].cb([{type:'attributes',target:img}]);assert.equal(img.hasAttribute('data-haki-image-pending'),true);img.complete=true;img.naturalWidth=400;img.emit('load');assert.equal(img.hasAttribute('data-haki-image-pending'),false)});
test('Actual weekly loader rejects obsolete data and retains current inventory',async()=>{const s=fs.readFileSync(new URL('../admin/sales.js',import.meta.url),'utf8');const start=s.indexOf('let weekRequest=0;'),end=s.indexOf('\nfunction renderWeek()',start);const pending=[];let weekPaints=0,inventoryPaints=0;const state={weekStart:'2026-10-05'};const context={state,encodeURIComponent,mondayOf:d=>d,$:()=>new Element(),$$:()=>[],window:{HAKI_UI:{begin:()=>()=>{}}},api:()=>new Promise(resolve=>pending.push(resolve)),renderWeek:()=>weekPaints++,renderInventory:()=>inventoryPaints++};vm.createContext(context);vm.runInContext(s.slice(start,end),context);const old=context.loadWeek();state.weekStart='2026-10-12';const current=context.loadWeek();pending[1]({sales:[{fecha:'2026-10-12',id:'current'}],inventory:{A:{S:9}}});await current;pending[0]({sales:[{fecha:'2026-10-05',id:'old'}],inventory:{A:{S:1}}});await old;assert.equal(state.sales[0].id,'current');assert.equal(state.inventory.A.S,9);assert.equal(weekPaints,1);assert.equal(inventoryPaints,1)});
test('Loaded product/photo/color/size/cart routines and operational data files preserve the previous local phase',()=>{
 const baseline=JSON.parse(fs.readFileSync(new URL('./motion-baseline.json',import.meta.url),'utf8'));
 const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
 for(const [p,expected]of Object.entries(baseline.files))assert.equal(hash(fs.readFileSync(new URL('../'+p,import.meta.url))),expected,p);
 for(const item of baseline.sections){const now=fs.readFileSync(new URL('../'+item.file,import.meta.url),'utf8');const a=now.indexOf(item.start),b=now.indexOf(item.end,a);assert.ok(a>=0&&b>a,item.file);assert.equal(hash(now.slice(a,b)),item.sha256,item.file+item.start);}
});
test('The active suite receives one tab action while the legacy fallback stays usable',()=>{
 const s=fs.readFileSync(new URL('../admin/sales.js',import.meta.url),'utf8');const line=s.split('\n').find(l=>l.startsWith("$$('.tab').forEach"));let legacy=0,suite=0;const listeners=[];const button={dataset:{tab:'archived'},addEventListener:(_,cb)=>listeners.push(cb)};
 const context={$$:()=>[button],switchTab:()=>legacy++,window:{hakiSetPanel:()=>suite++}};vm.runInNewContext(line,context);button.addEventListener('click',()=>context.window.hakiSetPanel(button.dataset.tab));listeners.forEach(cb=>cb());assert.equal(legacy,0);assert.equal(suite,1);delete context.window.hakiSetPanel;listeners[0]();assert.equal(legacy,1);
});
test('Actual archive requests cannot let an older response overwrite newer data',async()=>{
 const s=fs.readFileSync(new URL('../admin/sales.js',import.meta.url),'utf8');const a=s.indexOf('let archivedRequest=0;'),b=s.indexOf('\n',s.indexOf('async function loadArchivedSales()',a));const pending=[];let renders=0;const state={};const context={state,$:()=>new Element(),window:{HAKI_UI:{begin:()=>()=>{}}},api:()=>new Promise(resolve=>pending.push(resolve)),renderArchivedSales:()=>renders++};vm.createContext(context);vm.runInContext(s.slice(a,b),context);const old=context.loadArchivedSales(),fresh=context.loadArchivedSales();pending[1]({archived:[{id:'new'}]});await fresh;pending[0]({archived:[{id:'old'}]});await old;assert.equal(state.archived[0].id,'new');assert.equal(renders,1);
});
